#!/bin/bash
#PBS -l select=1:ncpus=17:mpiprocs=17:mem=100gb
#PBS -l walltime=06:00:00
#PBS -N mdsconversion
#PBS -P 11003280
#PBS -j oe
#PBS -o /home/users/nus/huangyl/scratch/code/llm-foundry/log/mdsconversion13.out

# load modules
module load miniforge3/23.10

# set envvars
export HF_HOME="/home/project/11003280/vault/cache_yuli"
source /home/users/nus/huangyl/scratch/code/nscc_working/arf/mosaicml_workspace/credential/hf_token
source activate /home/project/11003280/envs/llmfoundry_yuli

# Change directory to the directory containing the data preparation script
cd /home/users/nus/huangyl/scratch/code/llm-foundry/scripts/data_prep
sleep 30

python convert_dataset_json_mp.py \
    --path "/home/users/nus/huangyl/scratch/data/3lang/raw/en_hq/combined.jsonl" \
    --out_root "/home/users/nus/huangyl/scratch/data/3lang/out_llama3/en_hq/" \
    --log_file_path "/home/users/nus/huangyl/scratch/code/llm-foundry/log/mdsconversion13.out" \
    --num_processes 17 \
    --concat_tokens 8192 \
    --tokenizer "meta-llama/Meta-Llama-3-8B" \
    --chunk_size 300000 \
    --bos_text "<|begin_of_text|>" \
    --eos_text "<|end_of_text|>" \
    --compression "zstd" \
    |& tee -a "$log_file"


